# Generated by Django 3.0.2 on 2020-06-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_jsondata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('activity_models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_jsondata.Post')),
            ],
        ),
    ]
