# Generated by Django 3.0.2 on 2020-06-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_jsondata', '0002_auto_20200626_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
