# Generated by Django 3.0.2 on 2020-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_jsondata', '0004_auto_20200626_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TextField(),
        ),
    ]
